### ISSUE TITLE
Send out the announcement for upcoming Sunday

### ISSUE THREAD

**Issue by regnerjr** [iOS-Connect/SundayInstagramApp#2]
We have plans [Detailed here](https://github.com/iOS-Connect/sc-ios-connect/blob/master/SundayWalmartApp.md) to build an app on this coming Sunday. 

We should send an email to the group letting them know the cool thing we are going to do!
- [x] What is the email address to send the message to so it gets to our meet up members?
- [x] Is the message correct, clear, exciting?
- [x] Did we send it?

**Comment by regnerjr** [comment]
The email address to send announcements to is 

SantaClara-iOS-announce@meetup.com

**Comment by jayhu93** [comment]
I think the description is exciting! I can't wait to go after reading the description! who wouldn't want to implement their own Instagram! 👯

**Comment by jayhu93** [comment]
What do you think?

**Comment by regnerjr** [comment]
I think we'll keep this one separate from the month long instagram one. 
My plan is for this one to just be a one or 2 week, collection views, rest api son parsing thing. 
Then for october we'll plan a bigger app, basically a custom "Friendstagram" with firebase backend, probably core data on the device (or at least a caching layer) and hopefully some animations and visual polish.

**Comment by jayhu93** [comment]
The updated description reads great! I think it's ready to send! Would you do the honor? :D

**Comment by regnerjr** [comment]
Will you send? Please.

**Comment by jayhu93** [comment]
Not a problem at all!

**Comment by jayhu93** [comment]
I will go out for a bit after sending out the email,  should be able to contribute on the 4-week outline tomorrow!

**Comment by jayhu93** [comment]
Sent! Anyway to confirm?

**Comment by jayhu93** [comment]
Looks like it is on the message board!

**Comment by regnerjr** [comment]
I got the email! Closing this issue.
